#! /bin/sh

 ### BEGIN INIT INFO
 # Provides:          launch_blue
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Launche script blue
 ### END INIT INFO

 #change /direct/path/to/your/application to the path your application is in.
 cd /usr/share/bluecheck      # example cd /home/pi/myprogram/

 #change YourProgramExactName to Exact name of your program that you want to auto start
 python bluecheck.py

 exit 0 
